//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
/* tslint:disable */
import thrift = require("thrift");
import Thrift = thrift.Thrift;
import Q = thrift.Q;

/**
 * プロセス状態
 */
export enum ProcessStatusType {
	"FINISHED" = 0,
	"INSTANCE_CRASHED" = 1,
	"VIDEO_STOPPED" = 2,
	"INFINITY_LOOP_DETECTED" = 3,
}

export enum ErrorCode {
	"UNKNOWN" = 0,
	"SYSTEM_ERROR" = 1,
	"PARAMETER_ERROR" = 2,
	"CLUSTER_ERROR" = 3,
	"NOT_FOUND_ERROR" = 4,
	"NOT_MASTER_ERROR" = 5,
	"RECHECKING_MASTER_ERROR" = 6,
}

/**
 * クラスタに参加しているプログラムを識別する値
 */
export class ClusterIdentity {
	fqdn: string;
	type: string;
	name: string;
	czxid: string;
	constructor(args?: { fqdn?: string; type?: string; name?: string; czxid?: string }) {
		this.fqdn = null;
		this.type = null;
		this.name = null;
		this.czxid = null;
		if (args) {
			var args_ = args;
			if (args_.fqdn !== undefined) {
				this.fqdn = args_.fqdn;
			}
			if (args_.type !== undefined) {
				this.type = args_.type;
			}
			if (args_.name !== undefined) {
				this.name = args_.name;
			}
			if (args_.czxid !== undefined) {
				this.czxid = args_.czxid;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.fqdn = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.STRING) {
						this.type = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 3:
					if (ftype == Thrift.Type.STRING) {
						this.name = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 4:
					if (ftype == Thrift.Type.STRING) {
						this.czxid = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("ClusterIdentity");
		if (this.fqdn !== null && this.fqdn !== undefined) {
			output.writeFieldBegin("fqdn", Thrift.Type.STRING, 1);
			output.writeString(this.fqdn);
			output.writeFieldEnd();
		}
		if (this.type !== null && this.type !== undefined) {
			output.writeFieldBegin("type", Thrift.Type.STRING, 2);
			output.writeString(this.type);
			output.writeFieldEnd();
		}
		if (this.name !== null && this.name !== undefined) {
			output.writeFieldBegin("name", Thrift.Type.STRING, 3);
			output.writeString(this.name);
			output.writeFieldEnd();
		}
		if (this.czxid !== null && this.czxid !== undefined) {
			output.writeFieldBegin("czxid", Thrift.Type.STRING, 4);
			output.writeString(this.czxid);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

/**
 * クラスタに参加するための情報
 */
export class ProcessInfo {
	clusterIdentity: ClusterIdentity;
	port: number;
	machineValues: string;
	constructor(args?: { clusterIdentity?: ClusterIdentity; port?: number; machineValues?: string }) {
		this.clusterIdentity = null;
		this.port = null;
		this.machineValues = null;
		if (args) {
			var args_ = args;
			if (args_.clusterIdentity !== undefined) {
				this.clusterIdentity = args_.clusterIdentity;
			}
			if (args_.port !== undefined) {
				this.port = args_.port;
			}
			if (args_.machineValues !== undefined) {
				this.machineValues = args_.machineValues;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.clusterIdentity = new ClusterIdentity();
						this.clusterIdentity.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.I32) {
						this.port = input.readI32();
					} else {
						input.skip(ftype);
					}
					break;
				case 3:
					if (ftype == Thrift.Type.STRING) {
						this.machineValues = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("ProcessInfo");
		if (this.clusterIdentity !== null && this.clusterIdentity !== undefined) {
			output.writeFieldBegin("clusterIdentity", Thrift.Type.STRUCT, 1);
			this.clusterIdentity.write(output);
			output.writeFieldEnd();
		}
		if (this.port !== null && this.port !== undefined) {
			output.writeFieldBegin("port", Thrift.Type.I32, 2);
			output.writeI32(this.port);
			output.writeFieldEnd();
		}
		if (this.machineValues !== null && this.machineValues !== undefined) {
			output.writeFieldBegin("machineValues", Thrift.Type.STRING, 3);
			output.writeString(this.machineValues);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

/**
 * masterへのプロセス状態変化報告用情報
 */
export class ProcessStatusInfo {
	instanceId: string;
	type: ProcessStatusType;
	message: string;
	constructor(args?: { instanceId?: string; type?: ProcessStatusType; message?: string }) {
		this.instanceId = null;
		this.type = null;
		this.message = null;
		if (args) {
			var args_ = args;
			if (args_.instanceId !== undefined) {
				this.instanceId = args_.instanceId;
			}
			if (args_.type !== undefined) {
				this.type = args_.type;
			}
			if (args_.message !== undefined) {
				this.message = args_.message;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.instanceId = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.I32) {
						this.type = input.readI32();
					} else {
						input.skip(ftype);
					}
					break;
				case 3:
					if (ftype == Thrift.Type.STRING) {
						this.message = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("ProcessStatusInfo");
		if (this.instanceId !== null && this.instanceId !== undefined) {
			output.writeFieldBegin("instanceId", Thrift.Type.STRING, 1);
			output.writeString(this.instanceId);
			output.writeFieldEnd();
		}
		if (this.type !== null && this.type !== undefined) {
			output.writeFieldBegin("type", Thrift.Type.I32, 2);
			output.writeI32(this.type);
			output.writeFieldEnd();
		}
		if (this.message !== null && this.message !== undefined) {
			output.writeFieldBegin("message", Thrift.Type.STRING, 3);
			output.writeString(this.message);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

/**
 * インスタンス稼働時にinjectするモジュール
 */
export class Module {
	code: string;
	values: string;
	constructor(args?: { code?: string; values?: string }) {
		this.code = null;
		this.values = null;
		if (args) {
			var args_ = args;
			if (args_.code !== undefined) {
				this.code = args_.code;
			}
			if (args_.values !== undefined) {
				this.values = args_.values;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.code = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.STRING) {
						this.values = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Module");
		if (this.code !== null && this.code !== undefined) {
			output.writeFieldBegin("code", Thrift.Type.STRING, 1);
			output.writeString(this.code);
			output.writeFieldEnd();
		}
		if (this.values !== null && this.values !== undefined) {
			output.writeFieldBegin("values", Thrift.Type.STRING, 2);
			output.writeString(this.values);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

/**
 * インスタンス割り当て情報
 */
export class InstanceAssignment {
	instanceId: string;
	gameCode: string;
	entryPoint: string;
	modules: Module[];
	cost: number;
	playId: string;
	parentPlayIds: string[];
	constructor(args?: {
		instanceId?: string;
		gameCode?: string;
		entryPoint?: string;
		modules?: Module[];
		cost?: number;
		playId?: string;
		parentPlayIds?: string[];
	}) {
		this.instanceId = null;
		this.gameCode = null;
		this.entryPoint = null;
		this.modules = null;
		this.cost = null;
		this.playId = null;
		this.parentPlayIds = null;
		if (args) {
			var args_ = args;
			if (args_.instanceId !== undefined) {
				this.instanceId = args_.instanceId;
			}
			if (args_.gameCode !== undefined) {
				this.gameCode = args_.gameCode;
			}
			if (args_.entryPoint !== undefined) {
				this.entryPoint = args_.entryPoint;
			}
			if (args_.modules !== undefined) {
				this.modules = args_.modules;
			}
			if (args_.cost !== undefined) {
				this.cost = args_.cost;
			}
			if (args_.playId !== undefined) {
				this.playId = args_.playId;
			}
			if (args_.parentPlayIds !== undefined) {
				this.parentPlayIds = args_.parentPlayIds;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.instanceId = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.STRING) {
						this.gameCode = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 4:
					if (ftype == Thrift.Type.STRING) {
						this.entryPoint = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 5:
					if (ftype == Thrift.Type.LIST) {
						var _size0 = 0;
						var _rtmp34: any;
						this.modules = [];
						var _etype3 = 0;
						_rtmp34 = input.readListBegin();
						_etype3 = _rtmp34.etype;
						_size0 = _rtmp34.size;
						for (var _i5 = 0; _i5 < _size0; ++_i5) {
							var elem6: any = null;
							elem6 = new Module();
							elem6.read(input);
							this.modules.push(elem6);
						}
						input.readListEnd();
					} else {
						input.skip(ftype);
					}
					break;
				case 6:
					if (ftype == Thrift.Type.I32) {
						this.cost = input.readI32();
					} else {
						input.skip(ftype);
					}
					break;
				case 7:
					if (ftype == Thrift.Type.STRING) {
						this.playId = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 8:
					if (ftype == Thrift.Type.LIST) {
						var _size7 = 0;
						var _rtmp311: any;
						this.parentPlayIds = [];
						var _etype10 = 0;
						_rtmp311 = input.readListBegin();
						_etype10 = _rtmp311.etype;
						_size7 = _rtmp311.size;
						for (var _i12 = 0; _i12 < _size7; ++_i12) {
							var elem13: any = null;
							elem13 = input.readString();
							this.parentPlayIds.push(elem13);
						}
						input.readListEnd();
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("InstanceAssignment");
		if (this.instanceId !== null && this.instanceId !== undefined) {
			output.writeFieldBegin("instanceId", Thrift.Type.STRING, 1);
			output.writeString(this.instanceId);
			output.writeFieldEnd();
		}
		if (this.gameCode !== null && this.gameCode !== undefined) {
			output.writeFieldBegin("gameCode", Thrift.Type.STRING, 2);
			output.writeString(this.gameCode);
			output.writeFieldEnd();
		}
		if (this.entryPoint !== null && this.entryPoint !== undefined) {
			output.writeFieldBegin("entryPoint", Thrift.Type.STRING, 4);
			output.writeString(this.entryPoint);
			output.writeFieldEnd();
		}
		if (this.modules !== null && this.modules !== undefined) {
			output.writeFieldBegin("modules", Thrift.Type.LIST, 5);
			output.writeListBegin(Thrift.Type.STRUCT, this.modules.length);
			for (var iter14 in this.modules) {
				if (this.modules.hasOwnProperty(iter14)) {
					var value15 = this.modules[iter14];
					value15.write(output);
				}
			}
			output.writeListEnd();
			output.writeFieldEnd();
		}
		if (this.cost !== null && this.cost !== undefined) {
			output.writeFieldBegin("cost", Thrift.Type.I32, 6);
			output.writeI32(this.cost);
			output.writeFieldEnd();
		}
		if (this.playId !== null && this.playId !== undefined) {
			output.writeFieldBegin("playId", Thrift.Type.STRING, 7);
			output.writeString(this.playId);
			output.writeFieldEnd();
		}
		if (this.parentPlayIds !== null && this.parentPlayIds !== undefined) {
			output.writeFieldBegin("parentPlayIds", Thrift.Type.LIST, 8);
			output.writeListBegin(Thrift.Type.STRING, this.parentPlayIds.length);
			for (var iter16 in this.parentPlayIds) {
				if (this.parentPlayIds.hasOwnProperty(iter16)) {
					var value17 = this.parentPlayIds[iter16];
					output.writeString(value17);
				}
			}
			output.writeListEnd();
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

export class RPCError extends Thrift.TException {
	errorCode: ErrorCode;
	message: string;
	constructor(args?: { errorCode?: ErrorCode; message?: string }) {
		super("RPCError");
		this.name = "RPCError";
		this.errorCode = null;
		this.message = null;
		if (args) {
			var args_ = args;
			if (args_.errorCode !== undefined) {
				this.errorCode = args_.errorCode;
			}
			if (args_.message !== undefined) {
				this.message = args_.message;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.I32) {
						this.errorCode = input.readI32();
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.STRING) {
						this.message = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("RPCError");
		if (this.errorCode !== null && this.errorCode !== undefined) {
			output.writeFieldBegin("errorCode", Thrift.Type.I32, 1);
			output.writeI32(this.errorCode);
			output.writeFieldEnd();
		}
		if (this.message !== null && this.message !== undefined) {
			output.writeFieldBegin("message", Thrift.Type.STRING, 2);
			output.writeString(this.message);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

/**
 * プロセス種別gameRunnerを表す定数
 */
export var TYPE_GAME_RUNNER_2: string = "gameRunner2";
