//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
/* tslint:disable */
import thrift = require("thrift");
import Thrift = thrift.Thrift;
import Q = thrift.Q;

import ttypes = require("./cluster_types");
import ProcessStatusType = ttypes.ProcessStatusType;
import ErrorCode = ttypes.ErrorCode;
import TYPE_GAME_RUNNER_2 = ttypes.TYPE_GAME_RUNNER_2;
import RPCError = ttypes.RPCError;
import ClusterIdentity = ttypes.ClusterIdentity;
import ProcessInfo = ttypes.ProcessInfo;
import ProcessStatusInfo = ttypes.ProcessStatusInfo;
import Module = ttypes.Module;
import InstanceAssignment = ttypes.InstanceAssignment;
//HELPER FUNCTIONS AND STRUCTURES

class Master_join_args {
	processInfo: ProcessInfo;
	constructor(args?: { processInfo?: ProcessInfo }) {
		this.processInfo = null;
		if (args) {
			var args_ = args;
			if (args_.processInfo !== undefined) {
				this.processInfo = args_.processInfo;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.processInfo = new ProcessInfo();
						this.processInfo.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Master_join_args");
		if (this.processInfo !== null && this.processInfo !== undefined) {
			output.writeFieldBegin("processInfo", Thrift.Type.STRUCT, 1);
			this.processInfo.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Master_join_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Master_join_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Master_leave_args {
	identity: ClusterIdentity;
	constructor(args?: { identity?: ClusterIdentity }) {
		this.identity = null;
		if (args) {
			var args_ = args;
			if (args_.identity !== undefined) {
				this.identity = args_.identity;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.identity = new ClusterIdentity();
						this.identity.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Master_leave_args");
		if (this.identity !== null && this.identity !== undefined) {
			output.writeFieldBegin("identity", Thrift.Type.STRUCT, 1);
			this.identity.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Master_leave_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Master_leave_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Master_reportInstanceStatus_args {
	identity: ClusterIdentity;
	status: ProcessStatusInfo;
	constructor(args?: { identity?: ClusterIdentity; status?: ProcessStatusInfo }) {
		this.identity = null;
		this.status = null;
		if (args) {
			var args_ = args;
			if (args_.identity !== undefined) {
				this.identity = args_.identity;
			}
			if (args_.status !== undefined) {
				this.status = args_.status;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.identity = new ClusterIdentity();
						this.identity.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 2:
					if (ftype == Thrift.Type.STRUCT) {
						this.status = new ProcessStatusInfo();
						this.status.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Master_reportInstanceStatus_args");
		if (this.identity !== null && this.identity !== undefined) {
			output.writeFieldBegin("identity", Thrift.Type.STRUCT, 1);
			this.identity.write(output);
			output.writeFieldEnd();
		}
		if (this.status !== null && this.status !== undefined) {
			output.writeFieldBegin("status", Thrift.Type.STRUCT, 2);
			this.status.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Master_reportInstanceStatus_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Master_reportInstanceStatus_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

/**
 * master側が実装し、参加する側が使用するRPCインターフェイス
 */
export class Client {
	private output: thrift.TTransport;
	private pClass: { new (trans: thrift.TTransport): thrift.TProtocol };
	private _seqid: number = 0;
	private _reqs: { [key: string]: any } = {};
	constructor(output: thrift.TTransport, pClass: { new (trans: thrift.TTransport): thrift.TProtocol }) {
		this.output = output;
		this.pClass = pClass;
	}
	seqid() {
		return this._seqid;
	}
	new_seqid() {
		return (this._seqid += 1);
	}
	join(processInfo: ProcessInfo, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_join(processInfo);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_join(processInfo);
		}
	}

	send_join(processInfo: ProcessInfo): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("join", Thrift.MessageType.CALL, this.seqid());
		var args = new Master_join_args();
		args.processInfo = processInfo;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_join(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Master_join_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
	leave(identity: ClusterIdentity, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_leave(identity);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_leave(identity);
		}
	}

	send_leave(identity: ClusterIdentity): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("leave", Thrift.MessageType.CALL, this.seqid());
		var args = new Master_leave_args();
		args.identity = identity;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_leave(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Master_leave_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
	reportInstanceStatus(identity: ClusterIdentity, status: ProcessStatusInfo, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_reportInstanceStatus(identity, status);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_reportInstanceStatus(identity, status);
		}
	}

	send_reportInstanceStatus(identity: ClusterIdentity, status: ProcessStatusInfo): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("reportInstanceStatus", Thrift.MessageType.CALL, this.seqid());
		var args = new Master_reportInstanceStatus_args();
		args.identity = identity;
		args.status = status;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_reportInstanceStatus(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Master_reportInstanceStatus_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
}
export class Processor {
	private _handler: MasterLike;
	constructor(handler: MasterLike) {
		this._handler = handler;
	}
	process(input: thrift.TProtocol, output: thrift.TProtocol): any {
		var r = input.readMessageBegin();
		if ((<any>this)["process_" + r.fname]) {
			return (<any>this)["process_" + r.fname].call(this, r.rseqid, input, output);
		} else {
			input.skip(Thrift.Type.STRUCT);
			input.readMessageEnd();
			var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, "Unknown function " + r.fname);
			output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
			x.write(output);
			output.writeMessageEnd();
			output.flush();
		}
	}

	process_join(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Master_join_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.join.length === 1) {
			Q.fcall<void>(this._handler.join.bind(this._handler), args.processInfo).then(
				function () {
					var result = new Master_join_result();
					output.writeMessageBegin("join", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Master_join_result(err);
						output.writeMessageBegin("join", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("join", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.join(args.processInfo, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Master_join_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("join", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("join", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}

	process_leave(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Master_leave_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.leave.length === 1) {
			Q.fcall<void>(this._handler.leave.bind(this._handler), args.identity).then(
				function () {
					var result = new Master_leave_result();
					output.writeMessageBegin("leave", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Master_leave_result(err);
						output.writeMessageBegin("leave", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("leave", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.leave(args.identity, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Master_leave_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("leave", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("leave", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}

	process_reportInstanceStatus(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Master_reportInstanceStatus_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.reportInstanceStatus.length === 2) {
			Q.fcall<void>(this._handler.reportInstanceStatus.bind(this._handler), args.identity, args.status).then(
				function () {
					var result = new Master_reportInstanceStatus_result();
					output.writeMessageBegin("reportInstanceStatus", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Master_reportInstanceStatus_result(err);
						output.writeMessageBegin("reportInstanceStatus", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("reportInstanceStatus", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.reportInstanceStatus(args.identity, args.status, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Master_reportInstanceStatus_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("reportInstanceStatus", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("reportInstanceStatus", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}
}
export interface MasterLike {
	join(processInfo: ProcessInfo, callback?: (err: any) => void): Q.IPromise<void>;
	leave(identity: ClusterIdentity, callback?: (err: any) => void): Q.IPromise<void>;
	reportInstanceStatus(identity: ClusterIdentity, status: ProcessStatusInfo, callback?: (err: any) => void): Q.IPromise<void>;
}
