//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
/* tslint:disable */
import thrift = require("thrift");
import Thrift = thrift.Thrift;
import Q = thrift.Q;

import ttypes = require("./cluster_types");
import ProcessStatusType = ttypes.ProcessStatusType;
import ErrorCode = ttypes.ErrorCode;
import TYPE_GAME_RUNNER_2 = ttypes.TYPE_GAME_RUNNER_2;
import RPCError = ttypes.RPCError;
import ClusterIdentity = ttypes.ClusterIdentity;
import ProcessInfo = ttypes.ProcessInfo;
import ProcessStatusInfo = ttypes.ProcessStatusInfo;
import Module = ttypes.Module;
import InstanceAssignment = ttypes.InstanceAssignment;
//HELPER FUNCTIONS AND STRUCTURES

class Process_assignInstance_args {
	instanceAssignment: InstanceAssignment;
	constructor(args?: { instanceAssignment?: InstanceAssignment }) {
		this.instanceAssignment = null;
		if (args) {
			var args_ = args;
			if (args_.instanceAssignment !== undefined) {
				this.instanceAssignment = args_.instanceAssignment;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.instanceAssignment = new InstanceAssignment();
						this.instanceAssignment.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_assignInstance_args");
		if (this.instanceAssignment !== null && this.instanceAssignment !== undefined) {
			output.writeFieldBegin("instanceAssignment", Thrift.Type.STRUCT, 1);
			this.instanceAssignment.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_assignInstance_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_assignInstance_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_unassignInstance_args {
	instanceId: string;
	constructor(args?: { instanceId?: string }) {
		this.instanceId = null;
		if (args) {
			var args_ = args;
			if (args_.instanceId !== undefined) {
				this.instanceId = args_.instanceId;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.instanceId = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_unassignInstance_args");
		if (this.instanceId !== null && this.instanceId !== undefined) {
			output.writeFieldBegin("instanceId", Thrift.Type.STRING, 1);
			output.writeString(this.instanceId);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_unassignInstance_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_unassignInstance_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_pauseInstance_args {
	instanceId: string;
	constructor(args?: { instanceId?: string }) {
		this.instanceId = null;
		if (args) {
			var args_ = args;
			if (args_.instanceId !== undefined) {
				this.instanceId = args_.instanceId;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.instanceId = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_pauseInstance_args");
		if (this.instanceId !== null && this.instanceId !== undefined) {
			output.writeFieldBegin("instanceId", Thrift.Type.STRING, 1);
			output.writeString(this.instanceId);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_pauseInstance_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_pauseInstance_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_resumeInstance_args {
	instanceId: string;
	constructor(args?: { instanceId?: string }) {
		this.instanceId = null;
		if (args) {
			var args_ = args;
			if (args_.instanceId !== undefined) {
				this.instanceId = args_.instanceId;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRING) {
						this.instanceId = input.readString();
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_resumeInstance_args");
		if (this.instanceId !== null && this.instanceId !== undefined) {
			output.writeFieldBegin("instanceId", Thrift.Type.STRING, 1);
			output.writeString(this.instanceId);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

class Process_resumeInstance_result {
	err: RPCError;
	constructor(args?: { err?: RPCError } | RPCError) {
		this.err = null;
		if (args instanceof RPCError) {
			this.err = args;
			return;
		}
		if (args) {
			var args_ = <{ err?: RPCError }>args;
			if (args_.err !== undefined) {
				this.err = args_.err;
			}
		}
	}
	read(input: thrift.TProtocol): void {
		input.readStructBegin();
		while (true) {
			var ret = input.readFieldBegin();
			var fname = ret.fname;
			var ftype = ret.ftype;
			var fid = ret.fid;
			if (ftype == Thrift.Type.STOP) {
				break;
			}
			switch (fid) {
				case 1:
					if (ftype == Thrift.Type.STRUCT) {
						this.err = new RPCError();
						this.err.read(input);
					} else {
						input.skip(ftype);
					}
					break;
				case 0:
					input.skip(ftype);
					break;
				default:
					input.skip(ftype);
			}
			input.readFieldEnd();
		}
		input.readStructEnd();
		return;
	}

	write(output: thrift.TProtocol): void {
		output.writeStructBegin("Process_resumeInstance_result");
		if (this.err !== null && this.err !== undefined) {
			output.writeFieldBegin("err", Thrift.Type.STRUCT, 1);
			this.err.write(output);
			output.writeFieldEnd();
		}
		output.writeFieldStop();
		output.writeStructEnd();
		return;
	}
}

export class Client {
	private output: thrift.TTransport;
	private pClass: { new (trans: thrift.TTransport): thrift.TProtocol };
	private _seqid: number = 0;
	private _reqs: { [key: string]: any } = {};
	constructor(output: thrift.TTransport, pClass: { new (trans: thrift.TTransport): thrift.TProtocol }) {
		this.output = output;
		this.pClass = pClass;
	}
	seqid() {
		return this._seqid;
	}
	new_seqid() {
		return (this._seqid += 1);
	}
	assignInstance(instanceAssignment: InstanceAssignment, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_assignInstance(instanceAssignment);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_assignInstance(instanceAssignment);
		}
	}

	send_assignInstance(instanceAssignment: InstanceAssignment): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("assignInstance", Thrift.MessageType.CALL, this.seqid());
		var args = new Process_assignInstance_args();
		args.instanceAssignment = instanceAssignment;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_assignInstance(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Process_assignInstance_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
	unassignInstance(instanceId: string, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_unassignInstance(instanceId);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_unassignInstance(instanceId);
		}
	}

	send_unassignInstance(instanceId: string): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("unassignInstance", Thrift.MessageType.CALL, this.seqid());
		var args = new Process_unassignInstance_args();
		args.instanceId = instanceId;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_unassignInstance(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Process_unassignInstance_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
	pauseInstance(instanceId: string, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_pauseInstance(instanceId);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_pauseInstance(instanceId);
		}
	}

	send_pauseInstance(instanceId: string): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("pauseInstance", Thrift.MessageType.CALL, this.seqid());
		var args = new Process_pauseInstance_args();
		args.instanceId = instanceId;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_pauseInstance(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Process_pauseInstance_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
	resumeInstance(instanceId: string, callback?: (err: any) => void): Q.IPromise<void> {
		this._seqid = this.new_seqid();
		if (callback === undefined) {
			var _defer = Q.defer<any>();
			this._reqs[this.seqid()] = function (error: any, result: any) {
				if (error) {
					_defer.reject(error);
				} else {
					_defer.resolve(result);
				}
			};
			this.send_resumeInstance(instanceId);
			return _defer.promise;
		} else {
			this._reqs[this.seqid()] = callback;
			this.send_resumeInstance(instanceId);
		}
	}

	send_resumeInstance(instanceId: string): void {
		var output = new this.pClass(this.output);
		output.writeMessageBegin("resumeInstance", Thrift.MessageType.CALL, this.seqid());
		var args = new Process_resumeInstance_args();
		args.instanceId = instanceId;
		args.write(output);
		output.writeMessageEnd();
		return this.output.flush();
	}

	recv_resumeInstance(input: thrift.TProtocol, mtype: Thrift.MessageType, rseqid: number) {
		var callback = this._reqs[rseqid] || function () {};
		delete this._reqs[rseqid];
		if (mtype == Thrift.MessageType.EXCEPTION) {
			var x = new Thrift.TApplicationException();
			x.read(input);
			input.readMessageEnd();
			return callback(x);
		}
		var result = new Process_resumeInstance_result();
		result.read(input);
		input.readMessageEnd();

		if (null !== result.err) {
			return callback(result.err);
		}
		callback(null);
	}
}
export class Processor {
	private _handler: ProcessLike;
	constructor(handler: ProcessLike) {
		this._handler = handler;
	}
	process(input: thrift.TProtocol, output: thrift.TProtocol): any {
		var r = input.readMessageBegin();
		if ((<any>this)["process_" + r.fname]) {
			return (<any>this)["process_" + r.fname].call(this, r.rseqid, input, output);
		} else {
			input.skip(Thrift.Type.STRUCT);
			input.readMessageEnd();
			var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, "Unknown function " + r.fname);
			output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
			x.write(output);
			output.writeMessageEnd();
			output.flush();
		}
	}

	process_assignInstance(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Process_assignInstance_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.assignInstance.length === 1) {
			Q.fcall<void>(this._handler.assignInstance.bind(this._handler), args.instanceAssignment).then(
				function () {
					var result = new Process_assignInstance_result();
					output.writeMessageBegin("assignInstance", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Process_assignInstance_result(err);
						output.writeMessageBegin("assignInstance", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("assignInstance", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.assignInstance(args.instanceAssignment, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Process_assignInstance_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("assignInstance", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("assignInstance", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}

	process_unassignInstance(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Process_unassignInstance_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.unassignInstance.length === 1) {
			Q.fcall<void>(this._handler.unassignInstance.bind(this._handler), args.instanceId).then(
				function () {
					var result = new Process_unassignInstance_result();
					output.writeMessageBegin("unassignInstance", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Process_unassignInstance_result(err);
						output.writeMessageBegin("unassignInstance", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("unassignInstance", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.unassignInstance(args.instanceId, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Process_unassignInstance_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("unassignInstance", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("unassignInstance", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}

	process_pauseInstance(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Process_pauseInstance_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.pauseInstance.length === 1) {
			Q.fcall<void>(this._handler.pauseInstance.bind(this._handler), args.instanceId).then(
				function () {
					var result = new Process_pauseInstance_result();
					output.writeMessageBegin("pauseInstance", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Process_pauseInstance_result(err);
						output.writeMessageBegin("pauseInstance", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("pauseInstance", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.pauseInstance(args.instanceId, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Process_pauseInstance_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("pauseInstance", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("pauseInstance", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}

	process_resumeInstance(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol) {
		var args = new Process_resumeInstance_args();
		args.read(input);
		input.readMessageEnd();
		if (this._handler.resumeInstance.length === 1) {
			Q.fcall<void>(this._handler.resumeInstance.bind(this._handler), args.instanceId).then(
				function () {
					var result = new Process_resumeInstance_result();
					output.writeMessageBegin("resumeInstance", Thrift.MessageType.REPLY, seqid);
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
				function (err) {
					var result: { write(output: thrift.TProtocol): any };
					if (err instanceof RPCError) {
						result = new Process_resumeInstance_result(err);
						output.writeMessageBegin("resumeInstance", Thrift.MessageType.REPLY, seqid);
					} else {
						result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
						output.writeMessageBegin("resumeInstance", Thrift.MessageType.EXCEPTION, seqid);
					}
					result.write(output);
					output.writeMessageEnd();
					output.flush();
				},
			);
		} else {
			this._handler.resumeInstance(args.instanceId, function (err) {
				var result: { write: (output: thrift.TProtocol) => void };
				if (err == null || err instanceof RPCError) {
					result = new Process_resumeInstance_result(err != null ? err : { success: undefined });
					output.writeMessageBegin("resumeInstance", Thrift.MessageType.REPLY, seqid);
				} else {
					result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
					output.writeMessageBegin("resumeInstance", Thrift.MessageType.EXCEPTION, seqid);
				}
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
		}
	}
}
export interface ProcessLike {
	assignInstance(instanceAssignment: InstanceAssignment, callback?: (err: any) => void): Q.IPromise<void>;
	unassignInstance(instanceId: string, callback?: (err: any) => void): Q.IPromise<void>;
	pauseInstance(instanceId: string, callback?: (err: any) => void): Q.IPromise<void>;
	resumeInstance(instanceId: string, callback?: (err: any) => void): Q.IPromise<void>;
}
