server:
  port: 17000
  portOffset: 0
# middleware
dispatchingRedis:
  host: redis
  port: 6379
  option:
    password: ""
# akashic system
apiConfigs:
  systemAPI:
    baseUrl: http://system-api-server:3100/
  clusterMonitorAPI:
    baseUrl: http://cluster-monitor-api-server:16000/
playlogServer:
  zookeeper:
    hosts:
      - host: zookeeper
        port: 2181
# application config
admin: true
log:
  appenders:
    access:
      type: console
      layout:
        type: basic
    out:
      type: console
      layout:
        type: basic
    error:
      type: console
      layout:
        type: basic
  categories:
    default:
      appenders:
        - out
      level: info
    access:
      appenders:
        - access
      level: info
    out:
      appenders:
        - out
      level: info
    error:
      appenders:
        - error
      level: info
